# generated by datamodel-codegen:
#   filename:  any_object.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Dict, Optional

from pydantic import BaseModel, Field


class Item(BaseModel):
    bar: Optional[Dict[str, object]] = Field(None, title='Bar')
    foo: str = Field(..., title='Foo')
